### ISSUE TITLE
is the code below deprecated? 

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/javascript-hand-written-templates#6]
This is essentially a copy/paste from the READme, and as pasted, it works in the browser as expected.  

The test file in my pull request has 3 options for the line of code testing whether index runs. 

  it('runs', () => {
    // expect(true).to.be.true    (original code, fails)
    expect(true).toEqual(true) // this passes
      // expect(true).toBe(true)  // this passes
  })
})

Am I correct, or is there some other way to pass the test in the lab as written?
the error you get is this:  

 0   -__,------,
 1   -__|  /\_/\ 
 0   -_~|_( x .x) 
     -_ ""  "" 

  0 passing (492ms)
  1 failing

  1) index runs:
     TypeError: Cannot read property 'be' of undefined
      at Context.it (test/index-test.js:16:20)

**Comment by gj** [comment]
Test files removed: 2c11a8b06c123996cc29327883268118e69c3dd1

Thanks @smithWEBtek !
