### ISSUE TITLE
Test for readme lab issue

### ISSUE THREAD

**Issue by DanielSeehausen** [learn-co-curriculum/javascript-hand-written-templates#9]
```  
  it('runs', () => {
    expect(true).to.be.true
  })
```
     TypeError: Cannot read property 'be' of undefined
      at Context.it (test/index-test.js:16:20)

**Comment by gj** [comment]
Test files removed: 2c11a8b06c123996cc29327883268118e69c3dd1

Thanks @DanielSeehausen !
